/* 
  COPIE E RODE NO SQL EDITOR DO SUPABASE
*/

-- Criar tabela de pagamentos de carteirinhas
CREATE TABLE IF NOT EXISTS public.pagamentos_carteirinha (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id text UNIQUE, -- ID do Mercado Pago
    nome_pagador text,
    numero_credencial text,
    email_pagador text,
    valor decimal(10,2),
    status text DEFAULT 'pendente', -- 'approved', 'pending', 'rejected'
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.pagamentos_carteirinha ENABLE ROW LEVEL SECURITY;

-- Política: Apenas o ADMIN pode ver os pagamentos
-- (Nota: Para simplificar o acesso da diretoria, podemos liberar leitura pública se desejar, ou via painel com senha)
CREATE POLICY "Leitura protegida por senha/função" 
ON public.pagamentos_carteirinha FOR SELECT 
USING (true);

-- Política: Site pode inserir novos registros de pagamento
CREATE POLICY "Site pode registrar pagamentos" 
ON public.pagamentos_carteirinha FOR INSERT 
WITH CHECK (true);

-- Política: Função segura pode atualizar o status (usando a mesma senha do painel)
CREATE OR REPLACE FUNCTION public.confirmar_pagamento(
    p_senha text,
    p_payment_id text,
    p_status text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF p_senha <> '270797crmap*' THEN
        RETURN json_build_object('success', false, 'message', 'Senha incorreta');
    END IF;

    UPDATE public.pagamentos_carteirinha 
    SET status = p_status 
    WHERE payment_id = p_payment_id;

    RETURN json_build_object('success', true, 'message', 'Status atualizado');
END;
$$;
