/* 
  COPIE E COLE ESTE CÓDIGO NO "SQL EDITOR" DO SEU SUPABASE E CLIQUE EM "RUN"
*/

-- 1. Criar a tabela de produtos
CREATE TABLE IF NOT EXISTS public.produtos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    descricao text,
    preco text,
    whatsapp text,
    foto_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS (Segurança)
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

-- 3. Política: Qualquer um pode VER os produtos
CREATE POLICY "Acesso público para leitura" 
ON public.produtos FOR SELECT 
USING (true);

-- 4. Função Segura para Adicionar/Deletar via Senha (sem precisar de login complexo)
-- Isso permite que o painel funcione de qualquer lugar com a senha que você definiu

CREATE OR REPLACE FUNCTION public.gerenciar_produto(
    p_acao text, -- 'inserir' ou 'deletar'
    p_senha text,
    p_id bigint DEFAULT NULL,
    p_nome text DEFAULT NULL,
    p_descricao text DEFAULT NULL,
    p_preco text DEFAULT NULL,
    p_whatsapp text DEFAULT NULL,
    p_foto_url text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- VERIFICAÇÃO DA SENHA (A que você me passou)
    IF p_senha <> '270797crmap*' THEN
        RETURN json_build_object('success', false, 'message', 'Senha incorreta');
    END IF;

    IF p_acao = 'inserir' THEN
        INSERT INTO public.produtos (nome, descricao, preco, whatsapp, foto_url)
        VALUES (p_nome, p_descricao, p_preco, p_whatsapp, p_foto_url);
        RETURN json_build_object('success', true, 'message', 'Produto adicionado!');
    
    ELSIF p_acao = 'deletar' THEN
        DELETE FROM public.produtos WHERE id = p_id;
        RETURN json_build_object('success', true, 'message', 'Produto removido!');
    ELSE
        RETURN json_build_object('success', false, 'message', 'Ação inválida');
    END IF;
END;
$$;

-- 5. Configurar Storage (Bucket para fotos)
-- Nota: Você também precisa ir em "Storage" no menu lateral e criar um bucket chamado "fotos-produtos" e marcar como "Public".
