/*
  SAÚDE CRMAP v2 — login por profissional, pacientes, 8 sessões grátis, repasse 10%
  Rode no SQL Editor do Supabase APÓS setup_saude_agenda.sql
*/

-- Configuração institucional
CREATE TABLE IF NOT EXISTS public.saude_config (
  chave text PRIMARY KEY,
  valor text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

INSERT INTO public.saude_config (chave, valor) VALUES
  ('sessoes_gratuitas', '8'),
  ('percentual_repasse_crmap', '10'),
  ('pix_crmap', 'Atualize o PIX da CRMAP com a diretoria (CNPJ/chave)'),
  ('mensagem_pagamento', 'A partir da 9ª sessão a consulta é PAGA. Informe a paciente e registre o valor. Envie 10% do valor ao PIX da CRMAP.')
ON CONFLICT (chave) DO NOTHING;

ALTER TABLE public.profissionais_saude
  ADD COLUMN IF NOT EXISTS senha_acesso text;

UPDATE public.profissionais_saude
SET senha_acesso = 'crmap' || id::text || '2026'
WHERE senha_acesso IS NULL OR trim(senha_acesso) = '';

-- Pacientes (WhatsApp obrigatório e único)
CREATE TABLE IF NOT EXISTS public.pacientes_crmap (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  telefone text NOT NULL,
  telefone_norm text NOT NULL,
  sessoes_realizadas integer NOT NULL DEFAULT 0 CHECK (sessoes_realizadas >= 0),
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (telefone_norm)
);

CREATE OR REPLACE FUNCTION public._normalizar_telefone(p_tel text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  d text;
BEGIN
  d := regexp_replace(COALESCE(p_tel, ''), '\D', '', 'g');
  IF length(d) >= 10 AND left(d, 2) = '55' THEN
    d := substring(d from 3);
  END IF;
  IF length(d) < 10 OR length(d) > 11 THEN
    RETURN NULL;
  END IF;
  RETURN d;
END;
$$;

ALTER TABLE public.consultas_agendadas
  ADD COLUMN IF NOT EXISTS paciente_id bigint REFERENCES public.pacientes_crmap(id),
  ADD COLUMN IF NOT EXISTS numero_sessao integer,
  ADD COLUMN IF NOT EXISTS tipo_cobranca text NOT NULL DEFAULT 'gratuita'
    CHECK (tipo_cobranca IN ('gratuita', 'paga')),
  ADD COLUMN IF NOT EXISTS valor_consulta numeric(10,2),
  ADD COLUMN IF NOT EXISTS valor_repasse_crmap numeric(10,2),
  ADD COLUMN IF NOT EXISTS repasse_confirmado boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS comunicou_pagamento boolean NOT NULL DEFAULT false;

-- Vincular consultas antigas a pacientes (telefone existente)
DO $$
DECLARE
  r record;
  v_norm text;
  v_pid bigint;
BEGIN
  FOR r IN
    SELECT id, nome_paciente, telefone
    FROM public.consultas_agendadas
    WHERE paciente_id IS NULL AND telefone IS NOT NULL AND trim(telefone) <> ''
  LOOP
    v_norm := public._normalizar_telefone(r.telefone);
    IF v_norm IS NULL THEN
      CONTINUE;
    END IF;
    INSERT INTO public.pacientes_crmap (nome, telefone, telefone_norm)
    VALUES (r.nome_paciente, trim(r.telefone), v_norm)
    ON CONFLICT (telefone_norm) DO UPDATE
      SET nome = EXCLUDED.nome, updated_at = timezone('utc'::text, now())
    RETURNING id INTO v_pid;
    IF v_pid IS NULL THEN
      SELECT id INTO v_pid FROM public.pacientes_crmap WHERE telefone_norm = v_norm;
    END IF;
    UPDATE public.consultas_agendadas SET paciente_id = v_pid WHERE id = r.id;
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public._saude_cfg(p_chave text)
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT valor FROM public.saude_config WHERE chave = p_chave LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public._saude_senha_coord_ok(p_senha text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT COALESCE(p_senha, '') IN ('270797crmap*', 'secretaria2026');
$$;

CREATE OR REPLACE FUNCTION public._saude_prof_ok(p_prof_id bigint, p_senha text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profissionais_saude
    WHERE id = p_prof_id AND ativo AND senha_acesso = p_senha
  );
$$;

CREATE OR REPLACE FUNCTION public._saude_sessoes_gratuitas()
RETURNS integer
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(NULLIF(public._saude_cfg('sessoes_gratuitas'), '')::integer, 8);
$$;

CREATE OR REPLACE FUNCTION public.login_profissional_saude(
  p_profissional_id bigint,
  p_senha text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_nome text;
BEGIN
  IF NOT public._saude_prof_ok(p_profissional_id, p_senha) THEN
    RETURN json_build_object('success', false, 'message', 'Profissional ou senha incorretos');
  END IF;
  SELECT nome INTO v_nome FROM public.profissionais_saude WHERE id = p_profissional_id;
  RETURN json_build_object(
    'success', true,
    'role', 'profissional',
    'profissional_id', p_profissional_id,
    'nome', v_nome
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.login_coordenacao_saude(p_senha text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public._saude_senha_coord_ok(p_senha) THEN
    RETURN json_build_object('success', false, 'message', 'Senha incorreta');
  END IF;
  RETURN json_build_object(
    'success', true,
    'role', 'coordenacao',
    'pix_crmap', public._saude_cfg('pix_crmap'),
    'sessoes_gratuitas', public._saude_sessoes_gratuitas(),
    'percentual_repasse', public._saude_cfg('percentual_repasse_crmap')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.resumo_paciente_saude(
  p_telefone text,
  p_profissional_id bigint DEFAULT NULL,
  p_senha_prof text DEFAULT NULL,
  p_senha_coord text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_norm text;
  v_pac record;
  v_proxima integer;
  v_limite integer;
BEGIN
  v_limite := public._saude_sessoes_gratuitas();

  IF p_senha_coord IS NOT NULL AND public._saude_senha_coord_ok(p_senha_coord) THEN
    NULL;
  ELSIF p_profissional_id IS NOT NULL AND public._saude_prof_ok(p_profissional_id, p_senha_prof) THEN
    NULL;
  ELSE
    RETURN json_build_object('success', false, 'message', 'Acesso negado');
  END IF;

  v_norm := public._normalizar_telefone(p_telefone);
  IF v_norm IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'WhatsApp inválido. Use DDD + número (10 ou 11 dígitos).');
  END IF;

  SELECT * INTO v_pac FROM public.pacientes_crmap WHERE telefone_norm = v_norm;
  IF NOT FOUND THEN
    v_proxima := 1;
    RETURN json_build_object(
      'success', true,
      'novo', true,
      'proxima_sessao', v_proxima,
      'sessoes_realizadas', 0,
      'limite_gratuitas', v_limite,
      'exige_pagamento', false,
      'mensagem', format('Nova paciente — esta será a sessão 1 de %s gratuitas.', v_limite)
    );
  END IF;

  v_proxima := v_pac.sessoes_realizadas + 1;
  RETURN json_build_object(
    'success', true,
    'novo', false,
    'paciente_id', v_pac.id,
    'nome', v_pac.nome,
    'telefone', v_pac.telefone,
    'proxima_sessao', v_proxima,
    'sessoes_realizadas', v_pac.sessoes_realizadas,
    'limite_gratuitas', v_limite,
    'exige_pagamento', v_proxima > v_limite,
    'mensagem', CASE
      WHEN v_proxima > v_limite THEN
        format('ATENÇÃO: sessão %s — ultrapassou as %s gratuitas. Consulta PAGA. Comunicar valor e repasse 10%% PIX CRMAP.', v_proxima, v_limite)
      WHEN v_proxima = v_limite THEN
        format('Última sessão gratuita (%s de %s). Na próxima, consulta paga.', v_proxima, v_limite)
      ELSE
        format('Sessão %s de %s gratuitas já realizadas + esta agendada.', v_proxima, v_limite)
    END
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.criar_consulta_saude_v2(
  p_modo text,
  p_profissional_id bigint,
  p_senha text,
  p_nome_paciente text,
  p_telefone text,
  p_data_consulta date,
  p_hora_inicio time,
  p_duracao_min integer,
  p_tipo_atendimento text,
  p_observacoes text,
  p_criado_por text DEFAULT NULL,
  p_comunicou_pagamento boolean DEFAULT false
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_norm text;
  v_pid bigint;
  v_proxima integer;
  v_limite integer;
  v_cobranca text;
  v_conflito bigint;
  v_cid bigint;
  v_repasse_pct numeric;
BEGIN
  v_limite := public._saude_sessoes_gratuitas();

  IF p_modo = 'coordenacao' THEN
    IF NOT public._saude_senha_coord_ok(p_senha) THEN
      RETURN json_build_object('success', false, 'message', 'Senha de coordenação incorreta');
    END IF;
  ELSIF p_modo = 'profissional' THEN
    IF NOT public._saude_prof_ok(p_profissional_id, p_senha) THEN
      RETURN json_build_object('success', false, 'message', 'Senha do profissional incorreta');
    END IF;
  ELSE
    RETURN json_build_object('success', false, 'message', 'Modo inválido');
  END IF;

  IF trim(COALESCE(p_nome_paciente, '')) = '' THEN
    RETURN json_build_object('success', false, 'message', 'Informe o nome da paciente');
  END IF;

  v_norm := public._normalizar_telefone(p_telefone);
  IF v_norm IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'WhatsApp obrigatório (DDD + número válido).');
  END IF;

  INSERT INTO public.pacientes_crmap (nome, telefone, telefone_norm)
  VALUES (trim(p_nome_paciente), trim(p_telefone), v_norm)
  ON CONFLICT (telefone_norm) DO UPDATE
    SET nome = EXCLUDED.nome, updated_at = timezone('utc'::text, now())
  RETURNING id INTO v_pid;

  IF v_pid IS NULL THEN
    SELECT id INTO v_pid FROM public.pacientes_crmap WHERE telefone_norm = v_norm;
  END IF;

  SELECT sessoes_realizadas INTO v_proxima FROM public.pacientes_crmap WHERE id = v_pid;
  v_proxima := COALESCE(v_proxima, 0) + 1;
  v_cobranca := CASE WHEN v_proxima > v_limite THEN 'paga' ELSE 'gratuita' END;

  IF v_proxima > v_limite AND NOT COALESCE(p_comunicou_pagamento, false) THEN
    RETURN json_build_object(
      'success', false,
      'message', 'Marque que comunicou à paciente sobre consulta PAGA (após as 8 sessões gratuitas).',
      'exige_pagamento', true,
      'proxima_sessao', v_proxima
    );
  END IF;

  SELECT c.id INTO v_conflito
  FROM public.consultas_agendadas c
  WHERE c.profissional_id = p_profissional_id
    AND c.data_consulta = p_data_consulta
    AND c.hora_inicio = p_hora_inicio
    AND c.status <> 'cancelada'
  LIMIT 1;

  IF v_conflito IS NOT NULL THEN
    RETURN json_build_object('success', false, 'message', 'Horário já ocupado para este profissional');
  END IF;

  INSERT INTO public.consultas_agendadas (
    profissional_id, paciente_id, nome_paciente, telefone,
    data_consulta, hora_inicio, duracao_min, tipo_atendimento, observacoes,
    criado_por, numero_sessao, tipo_cobranca, comunicou_pagamento
  ) VALUES (
    p_profissional_id, v_pid, trim(p_nome_paciente), trim(p_telefone),
    p_data_consulta, p_hora_inicio,
    COALESCE(NULLIF(p_duracao_min, 0), 50),
    COALESCE(NULLIF(trim(p_tipo_atendimento), ''), 'Acolhimento'),
    NULLIF(trim(p_observacoes), ''),
    NULLIF(trim(p_criado_por), ''),
    v_proxima, v_cobranca, COALESCE(p_comunicou_pagamento, false)
  )
  RETURNING id INTO v_cid;

  RETURN json_build_object(
    'success', true,
    'id', v_cid,
    'paciente_id', v_pid,
    'numero_sessao', v_proxima,
    'tipo_cobranca', v_cobranca,
    'exige_pagamento', v_proxima > v_limite,
    'pix_crmap', public._saude_cfg('pix_crmap'),
    'percentual_repasse', public._saude_cfg('percentual_repasse_crmap')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_consultas_saude_v2(
  p_modo text,
  p_senha text,
  p_profissional_id bigint DEFAULT NULL,
  p_data_inicio date DEFAULT NULL,
  p_data_fim date DEFAULT NULL,
  p_filtro_prof_id bigint DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  profissional_id bigint,
  profissional_nome text,
  paciente_id bigint,
  nome_paciente text,
  telefone text,
  data_consulta date,
  hora_inicio time,
  duracao_min integer,
  tipo_atendimento text,
  observacoes text,
  status text,
  numero_sessao integer,
  tipo_cobranca text,
  valor_consulta numeric,
  valor_repasse_crmap numeric,
  repasse_confirmado boolean,
  comunicou_pagamento boolean,
  sessoes_realizadas_paciente integer,
  criado_por text,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_modo = 'coordenacao' THEN
    IF NOT public._saude_senha_coord_ok(p_senha) THEN
      RAISE EXCEPTION 'Acesso negado';
    END IF;
  ELSIF p_modo = 'profissional' THEN
    IF NOT public._saude_prof_ok(p_profissional_id, p_senha) THEN
      RAISE EXCEPTION 'Acesso negado';
    END IF;
    p_filtro_prof_id := p_profissional_id;
  ELSE
    RAISE EXCEPTION 'Modo inválido';
  END IF;

  RETURN QUERY
  SELECT
    c.id,
    c.profissional_id,
    p.nome AS profissional_nome,
    c.paciente_id,
    c.nome_paciente,
    c.telefone,
    c.data_consulta,
    c.hora_inicio,
    c.duracao_min,
    c.tipo_atendimento,
    c.observacoes,
    c.status,
    c.numero_sessao,
    c.tipo_cobranca,
    c.valor_consulta,
    c.valor_repasse_crmap,
    c.repasse_confirmado,
    c.comunicou_pagamento,
    COALESCE(pc.sessoes_realizadas, 0) AS sessoes_realizadas_paciente,
    c.criado_por,
    c.created_at
  FROM public.consultas_agendadas c
  JOIN public.profissionais_saude p ON p.id = c.profissional_id
  LEFT JOIN public.pacientes_crmap pc ON pc.id = c.paciente_id
  WHERE (p_data_inicio IS NULL OR c.data_consulta >= p_data_inicio)
    AND (p_data_fim IS NULL OR c.data_consulta <= p_data_fim)
    AND (p_filtro_prof_id IS NULL OR c.profissional_id = p_filtro_prof_id)
  ORDER BY c.data_consulta ASC, c.hora_inicio ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_consulta_saude_v2(
  p_modo text,
  p_senha text,
  p_profissional_id bigint,
  p_id bigint,
  p_status text,
  p_observacoes text DEFAULT NULL,
  p_valor_consulta numeric DEFAULT NULL,
  p_repasse_confirmado boolean DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_c record;
  v_pct numeric;
  v_repasse numeric;
  v_limite integer;
BEGIN
  v_limite := public._saude_sessoes_gratuitas();
  v_pct := COALESCE(NULLIF(public._saude_cfg('percentual_repasse_crmap'), '')::numeric, 10) / 100.0;

  IF p_modo = 'coordenacao' THEN
    IF NOT public._saude_senha_coord_ok(p_senha) THEN
      RETURN json_build_object('success', false, 'message', 'Senha incorreta');
    END IF;
  ELSIF p_modo = 'profissional' THEN
    IF NOT public._saude_prof_ok(p_profissional_id, p_senha) THEN
      RETURN json_build_object('success', false, 'message', 'Senha incorreta');
    END IF;
  ELSE
    RETURN json_build_object('success', false, 'message', 'Modo inválido');
  END IF;

  SELECT c.*, pc.sessoes_realizadas AS sr
  INTO v_c
  FROM public.consultas_agendadas c
  LEFT JOIN public.pacientes_crmap pc ON pc.id = c.paciente_id
  WHERE c.id = p_id;

  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'Consulta não encontrada');
  END IF;

  IF p_modo = 'profissional' AND v_c.profissional_id <> p_profissional_id THEN
    RETURN json_build_object('success', false, 'message', 'Esta consulta pertence a outro profissional');
  END IF;

  IF p_status NOT IN ('agendada', 'realizada', 'cancelada', 'falta') THEN
    RETURN json_build_object('success', false, 'message', 'Status inválido');
  END IF;

  IF p_status = 'realizada' AND COALESCE(v_c.numero_sessao, 0) > v_limite THEN
    IF p_valor_consulta IS NULL OR p_valor_consulta <= 0 THEN
      RETURN json_build_object(
        'success', false,
        'message', format('Sessão %s é PAGA: informe o valor da consulta.', v_c.numero_sessao),
        'exige_valor', true
      );
    END IF;
    v_repasse := round((p_valor_consulta * v_pct)::numeric, 2);
  ELSE
    v_repasse := NULL;
    p_valor_consulta := NULL;
  END IF;

  UPDATE public.consultas_agendadas
  SET
    status = p_status,
    observacoes = COALESCE(NULLIF(trim(p_observacoes), ''), observacoes),
    valor_consulta = CASE WHEN p_status = 'realizada' THEN p_valor_consulta ELSE valor_consulta END,
    valor_repasse_crmap = CASE WHEN p_status = 'realizada' THEN v_repasse ELSE valor_repasse_crmap END,
    repasse_confirmado = COALESCE(p_repasse_confirmado, repasse_confirmado),
    updated_at = timezone('utc'::text, now())
  WHERE id = p_id;

  IF p_status = 'realizada' AND v_c.paciente_id IS NOT NULL AND v_c.status <> 'realizada' THEN
    UPDATE public.pacientes_crmap
    SET sessoes_realizadas = sessoes_realizadas + 1,
        updated_at = timezone('utc'::text, now())
    WHERE id = v_c.paciente_id;
  END IF;

  IF p_status IN ('cancelada', 'falta') AND v_c.status = 'realizada' AND v_c.paciente_id IS NOT NULL THEN
    UPDATE public.pacientes_crmap
    SET sessoes_realizadas = GREATEST(0, sessoes_realizadas - 1),
        updated_at = timezone('utc'::text, now())
    WHERE id = v_c.paciente_id;
  END IF;

  RETURN json_build_object(
    'success', true,
    'valor_repasse_crmap', v_repasse,
    'pix_crmap', public._saude_cfg('pix_crmap'),
    'percentual_repasse', public._saude_cfg('percentual_repasse_crmap')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.painel_resumo_saude(p_senha text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_limite integer;
BEGIN
  IF NOT public._saude_senha_coord_ok(p_senha) THEN
    RETURN json_build_object('success', false, 'message', 'Senha incorreta');
  END IF;
  v_limite := public._saude_sessoes_gratuitas();

  RETURN json_build_object(
    'success', true,
    'pix_crmap', public._saude_cfg('pix_crmap'),
    'sessoes_gratuitas', v_limite,
    'percentual_repasse', public._saude_cfg('percentual_repasse_crmap'),
    'pacientes_acima_limite', (
      SELECT COALESCE(json_agg(json_build_object(
        'nome', nome,
        'telefone', telefone,
        'sessoes_realizadas', sessoes_realizadas
      ) ORDER BY sessoes_realizadas DESC), '[]'::json)
      FROM public.pacientes_crmap
      WHERE sessoes_realizadas >= v_limite
    ),
    'repasses_pendentes', (
      SELECT COALESCE(json_agg(json_build_object(
        'id', c.id,
        'paciente', c.nome_paciente,
        'profissional', p.nome,
        'data_consulta', c.data_consulta,
        'numero_sessao', c.numero_sessao,
        'valor_consulta', c.valor_consulta,
        'valor_repasse_crmap', c.valor_repasse_crmap
      ) ORDER BY c.data_consulta DESC), '[]'::json)
      FROM public.consultas_agendadas c
      JOIN public.profissionais_saude p ON p.id = c.profissional_id
      WHERE c.status = 'realizada'
        AND c.tipo_cobranca = 'paga'
        AND COALESCE(c.valor_repasse_crmap, 0) > 0
        AND NOT c.repasse_confirmado
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_config_saude(
  p_senha text,
  p_pix_crmap text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public._saude_senha_coord_ok(p_senha) THEN
    RETURN json_build_object('success', false, 'message', 'Senha incorreta');
  END IF;
  IF p_pix_crmap IS NOT NULL AND trim(p_pix_crmap) <> '' THEN
    INSERT INTO public.saude_config (chave, valor, updated_at)
    VALUES ('pix_crmap', trim(p_pix_crmap), now())
    ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor, updated_at = now();
  END IF;
  RETURN json_build_object('success', true, 'pix_crmap', public._saude_cfg('pix_crmap'));
END;
$$;

GRANT EXECUTE ON FUNCTION public.login_profissional_saude(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.login_coordenacao_saude(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.resumo_paciente_saude(text, bigint, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.criar_consulta_saude_v2(text, bigint, text, text, text, date, time, integer, text, text, text, boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.listar_consultas_saude_v2(text, text, bigint, date, date, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_consulta_saude_v2(text, text, bigint, bigint, text, text, numeric, boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.painel_resumo_saude(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_config_saude(text, text) TO anon, authenticated;

ALTER TABLE public.saude_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Leitura config saude" ON public.saude_config;
CREATE POLICY "Leitura config saude" ON public.saude_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "Bloqueio pacientes" ON public.pacientes_crmap;
CREATE POLICY "Bloqueio pacientes" ON public.pacientes_crmap FOR ALL USING (false) WITH CHECK (false);
