/*
  AGENDA DE CONSULTAS — CRMAP /saúde
  Rode no SQL Editor do Supabase (projeto qzjvzbvoxwhggvadaroq).
*/

CREATE TABLE IF NOT EXISTS public.profissionais_saude (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  cargo text,
  ativo boolean NOT NULL DEFAULT true,
  ordem integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.consultas_agendadas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profissional_id bigint NOT NULL REFERENCES public.profissionais_saude(id),
  nome_paciente text NOT NULL,
  telefone text,
  data_consulta date NOT NULL,
  hora_inicio time NOT NULL,
  duracao_min integer NOT NULL DEFAULT 50 CHECK (duracao_min > 0 AND duracao_min <= 240),
  tipo_atendimento text NOT NULL DEFAULT 'Acolhimento',
  observacoes text,
  status text NOT NULL DEFAULT 'agendada'
    CHECK (status IN ('agendada', 'realizada', 'cancelada', 'falta')),
  criado_por text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_consultas_data ON public.consultas_agendadas (data_consulta, hora_inicio);
CREATE INDEX IF NOT EXISTS idx_consultas_prof ON public.consultas_agendadas (profissional_id, data_consulta);

ALTER TABLE public.profissionais_saude ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultas_agendadas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura profissionais saude" ON public.profissionais_saude;
CREATE POLICY "Leitura profissionais saude"
ON public.profissionais_saude FOR SELECT USING (ativo = true);

DROP POLICY IF EXISTS "Bloqueio direto consultas" ON public.consultas_agendadas;
CREATE POLICY "Bloqueio direto consultas"
ON public.consultas_agendadas FOR ALL USING (false) WITH CHECK (false);

INSERT INTO public.profissionais_saude (nome, cargo, ordem)
SELECT v.nome, v.cargo, v.ordem
FROM (VALUES
  ('Fátima Maria de Jesus Chaves Soares', 'Dra. em Psicanálise — Coord. Saúde Mental', 1),
  ('Jórsia Chaves Horta Nascimento', 'Psicanalista — Vice / Diretora Saúde Mental', 2),
  ('Rosilaine Ribeiro de Moura Rocha', 'Psicóloga', 3),
  ('Márcia Rodrigues Daian', 'Psicóloga', 4),
  ('Érika Danúbia da Silva', 'Assistente de Saúde', 5)
) AS v(nome, cargo, ordem)
WHERE NOT EXISTS (SELECT 1 FROM public.profissionais_saude LIMIT 1);

CREATE OR REPLACE FUNCTION public._saude_senha_ok(p_senha text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT COALESCE(p_senha, '') = '270797crmap*';
$$;

CREATE OR REPLACE FUNCTION public.listar_consultas_saude(
  p_senha text,
  p_data_inicio date DEFAULT NULL,
  p_data_fim date DEFAULT NULL,
  p_profissional_id bigint DEFAULT NULL
)
RETURNS SETOF public.consultas_agendadas
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public._saude_senha_ok(p_senha) THEN
    RAISE EXCEPTION 'Acesso negado';
  END IF;

  RETURN QUERY
  SELECT c.*
  FROM public.consultas_agendadas c
  WHERE (p_data_inicio IS NULL OR c.data_consulta >= p_data_inicio)
    AND (p_data_fim IS NULL OR c.data_consulta <= p_data_fim)
    AND (p_profissional_id IS NULL OR c.profissional_id = p_profissional_id)
  ORDER BY c.data_consulta ASC, c.hora_inicio ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public.criar_consulta_saude(
  p_senha text,
  p_profissional_id bigint,
  p_nome_paciente text,
  p_telefone text,
  p_data_consulta date,
  p_hora_inicio time,
  p_duracao_min integer,
  p_tipo_atendimento text,
  p_observacoes text,
  p_criado_por text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id bigint;
  v_conflito bigint;
BEGIN
  IF NOT public._saude_senha_ok(p_senha) THEN
    RETURN json_build_object('success', false, 'message', 'Senha incorreta');
  END IF;

  IF trim(COALESCE(p_nome_paciente, '')) = '' THEN
    RETURN json_build_object('success', false, 'message', 'Informe o nome da paciente');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.profissionais_saude WHERE id = p_profissional_id AND ativo) THEN
    RETURN json_build_object('success', false, 'message', 'Profissional inválido');
  END IF;

  SELECT c.id INTO v_conflito
  FROM public.consultas_agendadas c
  WHERE c.profissional_id = p_profissional_id
    AND c.data_consulta = p_data_consulta
    AND c.hora_inicio = p_hora_inicio
    AND c.status <> 'cancelada'
  LIMIT 1;

  IF v_conflito IS NOT NULL THEN
    RETURN json_build_object('success', false, 'message', 'Horário já ocupado para este profissional');
  END IF;

  INSERT INTO public.consultas_agendadas (
    profissional_id, nome_paciente, telefone, data_consulta, hora_inicio,
    duracao_min, tipo_atendimento, observacoes, criado_por
  ) VALUES (
    p_profissional_id,
    trim(p_nome_paciente),
    NULLIF(trim(p_telefone), ''),
    p_data_consulta,
    p_hora_inicio,
    COALESCE(NULLIF(p_duracao_min, 0), 50),
    COALESCE(NULLIF(trim(p_tipo_atendimento), ''), 'Acolhimento'),
    NULLIF(trim(p_observacoes), ''),
    NULLIF(trim(p_criado_por), '')
  )
  RETURNING id INTO v_id;

  RETURN json_build_object('success', true, 'id', v_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_status_consulta_saude(
  p_senha text,
  p_id bigint,
  p_status text,
  p_observacoes text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public._saude_senha_ok(p_senha) THEN
    RETURN json_build_object('success', false, 'message', 'Senha incorreta');
  END IF;

  IF p_status NOT IN ('agendada', 'realizada', 'cancelada', 'falta') THEN
    RETURN json_build_object('success', false, 'message', 'Status inválido');
  END IF;

  UPDATE public.consultas_agendadas
  SET
    status = p_status,
    observacoes = COALESCE(NULLIF(trim(p_observacoes), ''), observacoes),
    updated_at = timezone('utc'::text, now())
  WHERE id = p_id;

  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'Consulta não encontrada');
  END IF;

  RETURN json_build_object('success', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.listar_consultas_saude(text, date, date, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.criar_consulta_saude(text, bigint, text, text, date, time, integer, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_status_consulta_saude(text, bigint, text, text) TO anon, authenticated;
